<!DOCTYPE html>
<html lang="en">

<head>
    <title>
        <?=$title; ?>
    </title>
</head>

<body>
    <h1><?=$title; ?></h1>
<?php include __DIR__ . '/nav.phtml';
echo "</br></br>";
if(!empty($user)){
?>
<table>
    <tr>
        <td>ID</td>
		<td><?=$user['id']; ?></td>
	</tr>
	<tr>
        <td>Username</td>
		<td><a href="/active-users/<?=$user['id']; ?>"><?=$user['username']; ?></a></td>
	</tr>
	<tr>
        <td>Email Address</td>
		<td><?=$user['email']; ?></td>
	</tr>
</table>
<?php } else {
	echo "User Info Not Found";
}
?>
</body>

</html>
